service:
  name: nginx_service      
  identifier: nginxservice   

  serviceDefinition:
    type: Kubernetes         
    spec:
      manifests:
        - manifest:
            identifier: nginx   
            spec:
              store:
                type: Github    
                spec:
                  connectorRef: nginxgitconnector  
                  gitFetchType: Main
                  manifests:
                    - path: "k8s/nginx-deployment.yaml"
                    - path: "k8s/nginx-service.yaml" 
                  repoName: harness  
                  branch: main                    
              skipResourceVersioning: false         
              enableDeclarativeRollback: false      
  gitOpsEnabled: false               
