service:
  name: nginx-service      
  identifier: nginxservice   

  serviceDefinition:
    type: Kubernetes         
    spec:
      manifests:
        - manifest:
            identifier: nginx   
            spec:
              store:
                type: Github    
                spec:
                  connectorRef: nginxgitconnector  
                  gitFetchType: Main
                  repoName: harness
                  branch: main
                  paths:
                   - "nginx-deployment.yaml"
                   - "nginx-svc.yaml"
                  folderpath: "/"               
              skipResourceVersioning: false         
              enableDeclarativeRollback: false      
  gitOpsEnabled: false               
